name: Qoder Assistant
on:
  issue_comment:
    types: [created]
permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
jobs:
  assistant:
    if: contains(github.event.comment.body, '@qoder') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - uses: QoderAI/qoder-action@v0
        with:
          qoder_personal_access_token: ${{ secrets.QODER_PERSONAL_ACCESS_TOKEN }}
          prompt: |
            ${{ github.event.comment.body }}
            REPO:${{ github.repository }} PR_NUMBER:${{ github.event.issue.number }}
